version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/django-weather-app

  - source: nginx/weather.conf
    destination: /etc/nginx/conf.d/
    overwrite: true
  
  - source: gunicorn/gunicorn.service
    destination: /etc/systemd/system/
    overwrite: true

permissions:
  - object: /home/ec2-user/django-weather-app
    pattern: '**'
    mode: '0755'
    owern: root
    group: root
    type:
      - file
      - directory
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 20
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root