version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/django-weather-app

  - source: nginx/weather.conf
    destination: /etc/nginx/conf.d/
    overwrite: true
  
  - source: gunicorn/gunicorn.service
    destination: /etc/systemd/system/
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 20
      runas: ec2-user

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user