version: 0.2

phases:
  install:
    commands:
      - echo "Setting executable permissions for scripts..."
      - chmod +x scripts/*.sh
  build:
    commands:
      - echo "Build complete"
artifacts:
  files:
    - '**/*'